# Generated by Django 5.0.6 on 2025-08-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_area', models.CharField(max_length=100)),
                ('ag_category', models.CharField(blank=True, max_length=2, null=True)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_honors', models.BooleanField(default=False)),
                ('is_ap', models.BooleanField(default=False)),
                ('grad_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='requirements.requirementcategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
    ]
